apiVersion: v1
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    creationTimestamp: "2019-09-12T21:58:40Z"
    name: ngc-core-resource-limits
    namespace: ngc
    resourceVersion: "519713"
    selfLink: /api/v1/namespaces/ngc/limitranges/ngc-core-resource-limits
    uid: 7ae8f6f6-d5a8-11e9-9261-0aa1ee0ab0ca
  spec:
    limits:
    - default:
        cpu: 500m
        memory: 4Gi
      defaultRequest:
        cpu: 500m
        memory: 4Gi
      max:
        cpu: "2"
        memory: 6Gi
      type: Container
    - max:
        cpu: "2"
        memory: 12Gi
      type: Pod
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
